[package]
name = "macroquad-particles"
version = "0.1.0"
edition = "2021"

[dependencies.macroquad]
default-features = false
version = "0.4.13"

[dependencies.nanoserde]
optional = true
version = "0.1"